-- 更新紀錄
-- v1.00, 2020/09/30
-- 1. EQPT_INTRO加入欄位EI_TITLE
-- 2. ORDER_EQPT刪除主鍵OE_NO，改為複合主鍵(OE_EQPTNO, OE_OMNO)
-- 3. CAR_EQPT加入欄位CE_EXPGET和CE_EXPBACK
-- 4. 所有SEQUENCE加入NOCACHE

-- 刪除所有表格
DROP TABLE MYFAV;
DROP TABLE CNOTICE;
DROP TABLE VNOTICE;
DROP TABLE MESSAGE;
DROP TABLE FAQ;
DROP TABLE ACTIVITY;
DROP TABLE EQPT_INTRO;
DROP TABLE GUIDE;
DROP TABLE WF_REPORT;
DROP TABLE WF_REPLY;
DROP TABLE WF_PIC;
DROP TABLE WATERFALL;
DROP TABLE AUTHORITY;
DROP TABLE ADMINIS;
DROP TABLE CAR_FOOD;
DROP TABLE CAR_EQPT;
DROP TABLE CAR_CAMP;
DROP TABLE ORDER_FOOD;
DROP TABLE ORDER_EQPT;
DROP TABLE ORDER_CAMP;
DROP TABLE ORDER_MASTER;
DROP TABLE MEMBERS;
DROP TABLE CGI_PIC;
DROP TABLE CG_INTRO;
DROP TABLE PROMO_FOOD;
DROP TABLE PROMO_EQPT;
DROP TABLE PROMO_CAMP;
DROP TABLE PROMOTION;
DROP TABLE FOOD;
DROP TABLE EQPT_AVAIL;
DROP TABLE EQUIPMENT;
DROP TABLE CAMP_AVAIL;
DROP TABLE CAMP;
DROP TABLE CAMP_TYPE;
DROP TABLE VENDOR;

-- 刪除SEQUENCE
DROP SEQUENCE SEQ_MEMNO;
DROP SEQUENCE SEQ_VDNO;
DROP SEQUENCE SEQ_ADMINISNO;
DROP SEQUENCE SEQ_AUTHNO;
DROP SEQUENCE SEQ_CAMPNO;
DROP SEQUENCE SEQ_CTNO;
DROP SEQUENCE SEQ_EQPTNO;
DROP SEQUENCE SEQ_FOODNO;
DROP SEQUENCE SEQ_PRONO;
DROP SEQUENCE SEQ_OMNO;
DROP SEQUENCE SEQ_WFNO;
DROP SEQUENCE SEQ_WFRNO;
DROP SEQUENCE SEQ_WFPNO;
DROP SEQUENCE SEQ_REPNO;
DROP SEQUENCE SEQ_CGINO;
DROP SEQUENCE SEQ_CGIPNO;
DROP SEQUENCE SEQ_CNNO;
DROP SEQUENCE SEQ_VNNO;
DROP SEQUENCE SEQ_MSGNO;
DROP SEQUENCE SEQ_GUIDENO;
DROP SEQUENCE SEQ_EINO;
DROP SEQUENCE SEQ_ACTNO;
DROP SEQUENCE SEQ_FAQNO;

-- 建立表格
CREATE TABLE VENDOR (
  VD_NO CHAR(10) PRIMARY KEY NOT NULL,
  VD_EMAIL VARCHAR2(30 CHAR) NOT NULL,
  VD_PWD VARCHAR2(20 CHAR) NOT NULL,
  VD_NAME VARCHAR2(10 CHAR) NOT NULL,
  VD_ID CHAR(10) NOT NULL,
  VD_BIRTH DATE,
  VD_MOBILE CHAR(10) NOT NULL,
  VD_CGNAME VARCHAR2(20 CHAR) NOT NULL,
  VD_CGTEL VARCHAR2(10 CHAR) NOT NULL,
  VD_CGADDR VARCHAR2(50 CHAR) NOT NULL,
  VD_TAXID CHAR(8) NOT NULL,
  VD_ACC VARCHAR2(17 CHAR) NOT NULL,
  VD_REGDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  VD_STAT NUMBER(1) DEFAULT 1 NOT NULL,
  VD_CGSTAT NUMBER(1) DEFAULT 1 NOT NULL,
  VD_LAT NUMBER(6,4),
  VD_LON NUMBER(7,4)
);

CREATE TABLE CAMP_TYPE (
    CT_NO CHAR(10) PRIMARY KEY NOT NULL,
    CT_NAME VARCHAR2(20 CHAR) NOT NULL
);

CREATE TABLE CAMP (
    CAMP_NO CHAR(10) PRIMARY KEY NOT NULL,
    CAMP_VDNO CHAR(10) NOT NULL,
    CAMP_NAME VARCHAR2(10 CHAR) NOT NULL,
    CAMP_CTNO CHAR(10),
    CAMP_QTY NUMBER(3) NOT NULL CHECK(CAMP_QTY > 0),
    CAMP_PRICE NUMBER(10) NOT NULL CHECK(CAMP_PRICE > 0),
    CAMP_STAT NUMBER(1) DEFAULT 0 NOT NULL,
    CAMP_PIC BLOB,
    CONSTRAINT FK_CAMP_VENDOR
    FOREIGN KEY(CAMP_VDNO) REFERENCES VENDOR(VD_NO),
    CONSTRAINT FK_CAMP_CAMPTYPE
    FOREIGN KEY(CAMP_CTNO) REFERENCES CAMP_TYPE(CT_NO)
);

CREATE TABLE CAMP_AVAIL (
    CA_CAMPNO CHAR(10) NOT NULL,
    CA_DATE DATE NOT NULL,
    CA_QTY NUMBER(3) NOT NULL CHECK(CA_QTY >= 0),
    CONSTRAINT CA_CAMPNO PRIMARY KEY(CA_CAMPNO, CA_DATE),
    CONSTRAINT FK_CAMPAVAIL_CAMP
    FOREIGN KEY(CA_CAMPNO) REFERENCES CAMP(CAMP_NO)
);

CREATE TABLE EQUIPMENT(
    EQPT_NO CHAR(10) PRIMARY KEY NOT NULL,
    EQPT_VDNO CHAR(10) NOT NULL,
    EQPT_NAME VARCHAR2(30 CHAR),
    EQPT_TYPE VARCHAR2(10 CHAR),
    EQPT_QTY NUMBER(10) CHECK (EQPT_QTY >= 0),
    EQPT_PRICE NUMBER(10) CHECK (EQPT_PRICE >= 0),
    EQPT_STAT NUMBER(1) DEFAULT 0 NOT NULL,
    EQPT_PIC BLOB,
    CONSTRAINT FK_EQUIPMENT_VENDOR
    FOREIGN KEY(EQPT_VDNO) REFERENCES VENDOR(VD_NO)
);

CREATE TABLE EQPT_AVAIL (
    EA_EQPTNO CHAR(10) NOT NULL,
    EA_DATE DATE NOT NULL,
    EA_QTY NUMBER(3) CHECK (EA_QTY >= 0),
    CONSTRAINT PK_EQPTAVAIL PRIMARY KEY(EA_EQPTNO, EA_DATE), 
    CONSTRAINT FK_EQPTAVAIL_EQUIPMENT
    FOREIGN KEY(EA_EQPTNO) REFERENCES EQUIPMENT(EQPT_NO)
);

CREATE TABLE FOOD (
    FOOD_NO CHAR(10) PRIMARY KEY NOT NULL,
    FOOD_VDNO CHAR(10) NOT NULL,
    FOOD_NAME VARCHAR2(10 CHAR) NOT NULL,
    FOOD_PRICE NUMBER(10) NOT NULL CHECK(FOOD_PRICE > 0),
    FOOD_INTRO VARCHAR2(100 CHAR),
    FOOD_STAT NUMBER(1) DEFAULT 0 NOT NULL,
    FOOD_PIC BLOB,
    CONSTRAINT FK_FOOD_VENDOR
    FOREIGN KEY(FOOD_VDNO) REFERENCES VENDOR(VD_NO)
);

CREATE TABLE PROMOTION (	
    PRO_NO CHAR(10 CHAR) PRIMARY KEY NOT NULL, 
	PRO_NAME VARCHAR2(30 CHAR),
	PRO_START DATE NOT NULL,
	PRO_END DATE NOT NULL,
	PRO_VDNO CHAR(10 CHAR) NOT NULL, 
	PRO_STAT NUMBER(1) DEFAULT 0 NOT NULL,
    CONSTRAINT FK_PROMOTION_VENDOR 
    FOREIGN KEY(PRO_VDNO) REFERENCES VENDOR(VD_NO)
);

CREATE TABLE PROMO_CAMP(
    PC_PRONO CHAR(10 CHAR) NOT NULL,
    PC_CAMPNO CHAR(10 CHAR) NOT NULL,
    PC_PRICE NUMBER(10,0) NOT NULL,
    CONSTRAINT PK_PROMO_CAMP PRIMARY KEY(PC_PRONO, PC_CAMPNO),
    CONSTRAINT FK_PROMOCAMP_PROMOTION
    FOREIGN KEY(PC_PRONO) REFERENCES PROMOTION(PRO_NO),
    CONSTRAINT FK_PROMOCAMP_CAMP 
    FOREIGN KEY(PC_CAMPNO) REFERENCES CAMP(CAMP_NO)
);

CREATE TABLE PROMO_EQPT(
    PE_PRONO CHAR(10 CHAR),
    PE_EQPTNO CHAR(10 CHAR),
    PE_PRICE NUMBER(10,0),
    CONSTRAINT PK_PROMO_EQPT PRIMARY KEY(PE_PRONO, PE_EQPTNO),
    CONSTRAINT FK_PROMOEQPT_PROMOTION
    FOREIGN KEY(PE_PRONO) REFERENCES PROMOTION(PRO_NO),
    CONSTRAINT FK_PROMOEQPT_EQUIPMENT
    FOREIGN KEY(PE_EQPTNO) REFERENCES EQUIPMENT(EQPT_NO)
);

CREATE TABLE PROMO_FOOD(
    PF_PRONO CHAR(10 CHAR) NOT NULL,
    PF_FOODNO CHAR(10 CHAR) NOT NULL,
    PF_PRICE NUMBER(10,0) NOT NULL,
    CONSTRAINT PK_PROMO_FOOD PRIMARY KEY(PF_PRONO, PF_FOODNO),
    CONSTRAINT FK_PROMOFOOD_PROMOTION
    FOREIGN KEY(PF_PRONO) REFERENCES PROMOTION(PRO_NO),
    CONSTRAINT FK_PROMOFOOD_FOOD
    FOREIGN KEY(PF_FOODNO) REFERENCES FOOD(FOOD_NO)
);

CREATE TABLE CG_INTRO (
    CGI_NO CHAR(10) PRIMARY KEY NOT NULL,
    CGI_VDNO CHAR(10) NOT NULL,
    CGI_CONTENT VARCHAR2(1000 CHAR),
    CGI_EDIT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_CGINTRO_VENDOR
    FOREIGN KEY(CGI_VDNO) REFERENCES VENDOR(VD_NO)
);

CREATE TABLE CGI_PIC (
    CGIP_NO CHAR(10) PRIMARY KEY NOT NULL,
    CGIP_CGINO CHAR(10) NOT NULL,
    CGIP_PIC BLOB,
    CONSTRAINT FK_CGIPIC_CGINTRO
    FOREIGN KEY(CGIP_CGINO) REFERENCES CG_INTRO(CGI_NO)
);

CREATE TABLE MEMBERS (
    MEM_NO CHAR(10) PRIMARY KEY NOT NULL,
    MEM_EMAIL VARCHAR2(30 CHAR) NOT NULL,
    MEM_PWD VARCHAR2(20 CHAR) NOT NULL,
    MEM_NAME VARCHAR2(10 CHAR) NOT NULL,
    MEM_ALIAS VARCHAR2(10 CHAR),
    MEM_GENDER CHAR(1 CHAR),
    MEM_BIRTH DATE NOT NULL,
    MEM_MOBILE CHAR(10) NOT NULL,
    MEM_TEL CHAR(10) NOT NULL,
    MEM_ADDR VARCHAR2(65 CHAR) NOT NULL,
    MEM_TYPE NUMBER(1)NOT NULL,
    MEM_REGDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MEM_STAT NUMBER(1) DEFAULT 1 NOT NULL
);

CREATE TABLE ORDER_MASTER(
    OM_NO CHAR(10 CHAR) PRIMARY KEY NOT NULL,
    OM_MEMNO CHAR(10 CHAR) NOT NULL,
    OM_VDNO CHAR(10 CHAR) NOT NULL,
    OM_STAT NUMBER(1) DEFAULT 1 NOT NULL,
    OM_NOTE VARCHAR2(100 CHAR),
    OM_ESTBL TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    OM_TXNAMT NUMBER(10,0),
    OM_TXNTIME TIMESTAMP,
    OM_CARDNO CHAR(16),
    CONSTRAINT FK_ORDERMASTER_MEMBERS
    FOREIGN KEY(OM_MEMNO) REFERENCES MEMBERS(MEM_NO),
    CONSTRAINT FK_ORDERMASTER_VENDOR
    FOREIGN KEY(OM_VDNO) REFERENCES VENDOR(VD_NO)
);

CREATE TABLE ORDER_CAMP (
    OC_CAMPNO CHAR(10) NOT NULL,
    OC_OMNO CHAR(10) NOT NULL,
    OC_QTY NUMBER(3) NOT NULL CHECK(OC_QTY > 0),
    OC_LISTPRICE NUMBER(10) NOT NULL CHECK(OC_LISTPRICE > 0),
    OC_PRICE NUMBER(10) NOT NULL CHECK(OC_PRICE > 0),
    OC_STAT NUMBER(1) DEFAULT 1 NOT NULL,
    OC_START DATE,
    OC_END DATE,
    OC_CHANGE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    OC_ESTBL TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_ORDERCAMP PRIMARY KEY(OC_CAMPNO, OC_OMNO),
    CONSTRAINT FK_ORDERCAMP_CAMP
    FOREIGN KEY(OC_CAMPNO) REFERENCES CAMP(CAMP_NO),
    CONSTRAINT FK_ORDERCAMP_ORDERMASTER
    FOREIGN KEY(OC_OMNO) REFERENCES ORDER_MASTER(OM_NO)
);

CREATE TABLE ORDER_EQPT (
  OE_EQPTNO CHAR(10) NOT NULL,
  OE_OMNO CHAR(10) NOT NULL,
  OE_QTY NUMBER(3) CHECK(OE_QTY > 0) NOT NULL,
  OE_LISTPRICE NUMBER(10) CHECK(OE_LISTPRICE > 0),
  OE_PRICE NUMBER(10) CHECK(OE_PRICE > 0) NOT NULL,
  OE_STAT NUMBER(1) DEFAULT 1 CHECK(OE_STAT = 0 or OE_STAT = 1) NOT NULL,
  OE_EXPGET DATE,
  OE_EXPBACK DATE,
  OE_GET TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  OE_BACK TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  OE_REQTY NUMBER(3),
  OE_CHANGE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  OE_ESTBL TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT PK_ORDEREQPT PRIMARY KEY(OE_EQPTNO, OE_OMNO),
  CONSTRAINT FK_ORDEREQPT_EQUIPMENT
  FOREIGN KEY(OE_EQPTNO) REFERENCES EQUIPMENT(EQPT_NO),
  CONSTRAINT FK_ORDEREQPT_ORDERMASTER
  FOREIGN KEY(OE_OMNO) REFERENCES ORDER_MASTER(OM_NO)
);

CREATE TABLE ORDER_FOOD (
    OF_FOODNO CHAR(10) NOT NULL,
    OF_OMNO CHAR(10) NOT NULL,
    OF_QTY NUMBER(3) NOT NULL CHECK(OF_QTY > 0),
    OF_LISTPRICE NUMBER(10) NOT NULL CHECK(OF_LISTPRICE > 0),
    OF_PRICE NUMBER(10) NOT NULL CHECK(OF_PRICE > 0),
    OF_STAT NUMBER(1) DEFAULT 1 NOT NULL,
    OF_CHANGE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    OF_ESTBL TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_ORDERFOOD PRIMARY KEY(OF_FOODNO, OF_OMNO),
    CONSTRAINT FK_ORDERFOOD_FOOD
    FOREIGN KEY(OF_FOODNO) REFERENCES FOOD(FOOD_NO),
    CONSTRAINT FK_ORDERFOOD_ORDERMASTER
    FOREIGN KEY(OF_OMNO) REFERENCES ORDER_MASTER(OM_NO)
);

CREATE TABLE CAR_CAMP (
    CC_CAMPNO CHAR(10) NOT NULL,
    CC_MEMNO CHAR(10) NOT NULL,
    CC_QTY NUMBER(3) NOT NULL CHECK(CC_QTY > 0),
    CC_START DATE NOT NULL,
    CC_END DATE NOT NULL,
    CONSTRAINT PK_CARCAMP PRIMARY KEY(CC_CAMPNO, CC_MEMNO),
    CONSTRAINT FK_CARCAMP_CAMP
    FOREIGN KEY(CC_CAMPNO) REFERENCES CAMP(CAMP_NO),
    CONSTRAINT FK_CARCAMP_MEMBERS
    FOREIGN KEY(CC_MEMNO) REFERENCES MEMBERS(MEM_NO)
);

CREATE TABLE CAR_EQPT (
    CE_EQPTNO CHAR(10) NOT NULL,
    CE_MEMNO CHAR(10) NOT NULL,
    CE_QTY NUMBER(3) CHECK (CE_QTY > 0),
    CE_EXPGET Date,
    CE_EXPBACK Date,
    CONSTRAINT CAR_EQP_PK PRIMARY KEY(CE_EQPTNO, CE_MEMNO),
    CONSTRAINT FK_CAREQPT_EQUIPMENT
    FOREIGN KEY(CE_EQPTNO) REFERENCES EQUIPMENT(EQPT_NO),
    CONSTRAINT FK_CAREQPT_MEMBERS
    FOREIGN KEY(CE_MEMNO) REFERENCES MEMBERS(MEM_NO)
);

CREATE TABLE CAR_FOOD (
    CF_FOODNO CHAR(10) NOT NULL,
    CF_MEMNO CHAR(10) NOT NULL,
    CF_QTY NUMBER(3) NOT NULL CHECK(CF_QTY > 0),
    CONSTRAINT PK_CARFOOD PRIMARY KEY(CF_FOODNO, CF_MEMNO),
    CONSTRAINT FK_CARFOOD_FOOD
    FOREIGN KEY(CF_FOODNO) REFERENCES FOOD(FOOD_NO),
    CONSTRAINT FK_CARFOOD_MEMBERS
    FOREIGN KEY(CF_MEMNO) REFERENCES MEMBERS(MEM_NO)    
);

CREATE TABLE ADMINIS (
    ADMINIS_NO CHAR(10) PRIMARY KEY NOT NULL,
    ADMINIS_NAME VARCHAR2(10 CHAR) NOT NULL,
    ADMINIS_PWD VARCHAR2(20 CHAR) NOT NULL,
    ADMINIS_EMAIL VARCHAR2(30 CHAR) NOT NULL,
    ADMINIS_DEPT VARCHAR2(10 CHAR),
    ADMINIS_REGDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ADMINIS_PV NUMBER(6) NOT NULL,
    ADMINIS_STAT NUMBER(1) DEFAULT 1 NOT NULL
);

CREATE TABLE AUTHORITY (
    AUTH_NO NUMBER(2) PRIMARY KEY NOT NULL,
    AUTH_NAME VARCHAR2(10 CHAR) NOT NULL
);

CREATE TABLE WATERFALL (
  WF_NO CHAR(10) PRIMARY KEY NOT NULL,
  WF_MEMNO CHAR(10) NOT NULL,
  WF_TITLE VARCHAR2(30 CHAR) NOT NULL,
  WF_CONTENT VARCHAR2(1000 CHAR) NOT NULL,
  WF_EDIT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  WF_STAT NUMBER(1) DEFAULT 1 NOT NULL,
  CONSTRAINT FK_WATERFALL_MEMBERS
  FOREIGN KEY(WF_MEMNO) REFERENCES MEMBERS(MEM_NO)
);

CREATE TABLE WF_PIC	(
  WFP_NO CHAR(10) PRIMARY KEY NOT NULL,
  WFP_WFNO CHAR(10) NOT NULL,
  WFP_PIC BLOB,
  CONSTRAINT FK_WFPIC_WATERFALL
  FOREIGN KEY(WFP_WFNO) REFERENCES WATERFALL(WF_NO)
);

CREATE TABLE WF_REPLY (
  WFR_NO CHAR(10) PRIMARY KEY NOT NULL,
  WFR_WFNO CHAR(10) NOT NULL,
  WFR_MEMNO CHAR(10) NOT NULL,
  WFR_CONTENT VARCHAR2(100 CHAR) NOT NULL,
  WFR_EDIT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  WFR_STAT NUMBER(1) DEFAULT 1 NOT NULL,
  CONSTRAINT FK_WFREPLY_WATERFALL
  FOREIGN KEY(WFR_WFNO) REFERENCES WATERFALL(WF_NO),
  CONSTRAINT FK_WFREPLY_MEMBERS
  FOREIGN KEY(WFR_MEMNO) REFERENCES MEMBERS(MEM_NO)
);

CREATE TABLE WF_REPORT (
  REP_NO CHAR(10) PRIMARY KEY NOT NULL,
  REP_WFNO CHAR(10) NOT NULL,
  REP_WFRNO CHAR(10),
  REP_MEMNO CHAR(10) NOT NULL,
  REP_ADMINISNO CHAR(10),
  REP_CONTENT VARCHAR2(100 CHAR),
  REP_STAT NUMBER(1) DEFAULT 0 NOT NULL,
  CONSTRAINT FK_WFREPORT_WATERFALL
  FOREIGN KEY(REP_WFNO) REFERENCES WATERFALL(WF_NO),
  CONSTRAINT FK_WFREPORT_WFREPLY
  FOREIGN KEY(REP_WFRNO) REFERENCES WF_REPLY(WFR_NO),
  CONSTRAINT FK_WFREPORT_MEMBERS
  FOREIGN KEY(REP_MEMNO) REFERENCES MEMBERS(MEM_NO),
  CONSTRAINT FK_WFREPORT_ADMINIS
  FOREIGN KEY(REP_ADMINISNO) REFERENCES ADMINIS(ADMINIS_NO)
);

CREATE TABLE GUIDE (
    GUIDE_NO CHAR(10) PRIMARY KEY NOT NULL,
    GUIDE_CONTENT VARCHAR2(300 CHAR),
    GUIDE_EDIT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    GUIDE_STAT NUMBER(1) DEFAULT 0 NOT NULL ,
    GUIDE_ADMINISNO CHAR(10) NOT NULL,
    CONSTRAINT FK_GUIDE_ADMINIS
    FOREIGN KEY(GUIDE_ADMINISNO) REFERENCES ADMINIS(ADMINIS_NO)
);

CREATE TABLE EQPT_INTRO (
  EI_NO CHAR(10) PRIMARY KEY NOT NULL,
  EI_TITLE VARCHAR2(30 CHAR) NOT NULL,
  EI_ADMINISNO CHAR(10) NOT NULL,
  EI_CONTENT VARCHAR2(300 CHAR) NOT NULL,
  EI_EDIT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  EI_STAT NUMBER(1) DEFAULT 0 NOT NULL,
  CONSTRAINT FK_EQPTINTRO_ADMINIS
  FOREIGN KEY(EI_ADMINISNO) REFERENCES ADMINIS(ADMINIS_NO)
);

CREATE TABLE ACTIVITY (
    ACT_NO CHAR(10) PRIMARY KEY NOT NULL,
    ACT_TITLE VARCHAR2(30 CHAR) NOT NULL,
    ACT_CONTENT VARCHAR2(1000 CHAR),
    ACT_EDIT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ACT_STAT NUMBER(1) DEFAULT 0 NOT NULL,
    ACT_ADMINISNO CHAR(10 CHAR),
    CONSTRAINT FK_ACTIVITY_ADMINIS
    FOREIGN KEY(ACT_ADMINISNO) REFERENCES ADMINIS(ADMINIS_NO)
);

CREATE TABLE FAQ (
    FAQ_NO CHAR(10) PRIMARY KEY NOT NULL,
    FAQ_TITLE VARCHAR2(30 CHAR) NOT NULL,
    FAQ_CONTENT VARCHAR2(300 CHAR),
    FAQ_EDIT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FAQ_STAT NUMBER(1) DEFAULT 0 NOT NULL,
    FAQ_ADMINISNO CHAR(10),
    CONSTRAINT FK_FAQ_ADMINIS
    FOREIGN KEY(FAQ_ADMINISNO) REFERENCES ADMINIS(ADMINIS_NO)  
);

CREATE TABLE MESSAGE(
    MSG_NO CHAR(10 CHAR) PRIMARY KEY NOT NULL,
    MSG_VDNO CHAR(10 CHAR) NOT NULL,
    MSG_MEMNO CHAR(10 CHAR) NOT NULL,
    MSG_CONTENT VARCHAR2(500 CHAR),
    MSG_TIME TIMESTAMP,
    MSG_SENDER NUMBER(1,0),
    CONSTRAINT FK_MESSAGE_VENDOR
    FOREIGN KEY(MSG_VDNO) REFERENCES VENDOR(VD_NO),
    CONSTRAINT FK_MESSAGE_MEMBERS 
    FOREIGN KEY(MSG_MEMNO) REFERENCES MEMBERS(MEM_NO)
);

CREATE TABLE VNOTICE (
  VN_NO CHAR(10) PRIMARY KEY NOT NULL,
  VN_VDNO CHAR(10) NOT NULL,          --FK VN_VDNO → VENDER VD_NO
  VN_CONTENT VARCHAR2(100 CHAR),
  VN_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT FK_VNOTICE_VENDOR
  FOREIGN KEY(VN_VDNO) REFERENCES VENDOR(VD_NO)
);

CREATE TABLE CNOTICE (
  CN_NO CHAR(10) PRIMARY KEY NOT NULL,
  CN_MEMNO CHAR(10) NOT NULL,
  CN_CONTENT VARCHAR2(100 CHAR),
  CN_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT FK_CNOTICE_MEMBERS
  FOREIGN KEY(CN_MEMNO) REFERENCES MEMBERS(MEM_NO)
);

CREATE TABLE MYFAV (
    MYFAV_MEMNO CHAR(10) NOT NULL,
    MYFAV_VDNO CHAR(10) NOT NULL,
    CONSTRAINT PK_MYFAV PRIMARY KEY(MYFAV_MEMNO, MYFAV_VDNO),
    CONSTRAINT FK_MYFAV_MEMBERS
    FOREIGN KEY(MYFAV_MEMNO) REFERENCES MEMBERS(MEM_NO),
    CONSTRAINT FK_MYFAV_VENDOR
    FOREIGN KEY(MYFAV_VDNO) REFERENCES VENDOR(VD_NO)
);

-- 建立自動編號
CREATE SEQUENCE SEQ_MEMNO      -- 會員編號
MAXVALUE 999999999
NOCYCLE
NOCACHE;

CREATE SEQUENCE SEQ_VDNO        -- 業者編號
MAXVALUE 999999999
NOCYCLE
NOCACHE;

CREATE SEQUENCE SEQ_ADMINISNO   -- 管理員編號
MAXVALUE 999999999
NOCYCLE
NOCACHE;

CREATE SEQUENCE SEQ_AUTHNO      -- 權限編號
MAXVALUE 99
NOCYCLE
NOCACHE;

CREATE SEQUENCE SEQ_CAMPNO      -- 營位編號
MAXVALUE 999999999
NOCYCLE
NOCACHE;

CREATE SEQUENCE SEQ_CTNO        -- 營位類型編號
MAXVALUE 99999999
NOCYCLE
NOCACHE;

CREATE SEQUENCE SEQ_EQPTNO      -- 裝備編號
MAXVALUE 999999999
NOCYCLE
NOCACHE;

CREATE SEQUENCE SEQ_FOODNO      -- 食材編號
MAXVALUE 999999999
NOCYCLE
NOCACHE;

CREATE SEQUENCE SEQ_PRONO       -- 促銷編號
MAXVALUE 999999999
NOCYCLE
NOCACHE;

CREATE SEQUENCE SEQ_OMNO        -- 主訂單編號
MAXVALUE 999999999
NOCYCLE
NOCACHE;

CREATE SEQUENCE SEQ_WFNO        -- 瀑布牆文章編號
MAXVALUE 999999999
NOCYCLE
NOCACHE;

CREATE SEQUENCE SEQ_WFRNO       -- 瀑布牆回覆編號
MAXVALUE 9999999
NOCYCLE
NOCACHE;

CREATE SEQUENCE SEQ_WFPNO       -- 瀑布牆圖片編號
MAXVALUE 9999999
NOCYCLE
NOCACHE;

CREATE SEQUENCE SEQ_REPNO       -- 瀑布牆檢舉編號
MAXVALUE 999999999
NOCYCLE
NOCACHE;

CREATE SEQUENCE SEQ_CGINO       -- 露營區介紹編號
MAXVALUE 999999999
NOCYCLE
NOCACHE;

CREATE SEQUENCE SEQ_CGIPNO      -- 露營區介紹圖片編號
MAXVALUE 99999999
NOCYCLE
NOCACHE;

CREATE SEQUENCE SEQ_CNNO        -- 客戶系統訊息編號
MAXVALUE 99999999
NOCYCLE
NOCACHE;

CREATE SEQUENCE SEQ_VNNO        -- 業者系統訊息編號
MAXVALUE 99999999
NOCYCLE
NOCACHE;

CREATE SEQUENCE SEQ_MSGNO       -- 私訊紀錄編號
MAXVALUE 9999999
NOCYCLE
NOCACHE;

CREATE SEQUENCE SEQ_GUIDENO     -- 露營指南編號
MAXVALUE 999999999
NOCYCLE
NOCACHE;

CREATE SEQUENCE SEQ_EINO        -- 裝備介紹編號
MAXVALUE 99999999
NOCYCLE
NOCACHE;

CREATE SEQUENCE SEQ_ACTNO       -- 活動快報編號
MAXVALUE 9999999
NOCYCLE
NOCACHE;

CREATE SEQUENCE SEQ_FAQNO       -- FAQ編號
MAXVALUE 9999999
NOCYCLE
NOCACHE;

-- 插入業者資料
INSERT INTO VENDOR
(VD_NO, VD_EMAIL, VD_PWD, VD_NAME, VD_ID,
VD_BIRTH, VD_MOBILE, VD_CGNAME, VD_CGTEL, VD_CGADDR, VD_TAXID,
VD_ACC, VD_STAT, VD_CGSTAT, VD_LAT, VD_LON)
VALUES('V' || LPAD(SEQ_VDNO.NEXTVAL, 9, '0'), 'summer_Raptor@gmail.com', 'winterpoultry', '夏猛禽', 'Z246801357',
to_date('2000-01-01', 'yyyy-mm-dd'), '0987878787', '愛禽海露營區', '048765432', '高雄市茂林區多納里大鬼湖1號', '23456789',
'12345678901234', 1, 0, 22.8725, 120.8617);

INSERT INTO VENDOR
(VD_NO, VD_EMAIL, VD_PWD, VD_NAME, VD_ID,
VD_BIRTH, VD_MOBILE, VD_CGNAME, VD_CGTEL, VD_CGADDR, VD_TAXID,
VD_ACC, VD_STAT, VD_CGSTAT, VD_LAT, VD_LON)
VALUES('V' || LPAD(SEQ_VDNO.NEXTVAL, 9, '0'), 'ubereats@yahoo.com.tw', 'ilovefoodpanda', '吳伯夷', 'W135792468',
to_date('1989-06-04', 'yyyy-mm-dd'), '0909090909', '媞峇蜜營區', '013456789', '宜蘭縣頭城鎮龜山島401號', '13572468',
'98765432109876', 1, 0, 24.8417, 121.9531);

INSERT INTO VENDOR
(VD_NO, VD_EMAIL, VD_PWD, VD_NAME, VD_ID,
VD_BIRTH, VD_MOBILE, VD_CGNAME, VD_CGTEL, VD_CGADDR, VD_TAXID,
VD_ACC, VD_STAT, VD_CGSTAT, VD_LAT, VD_LON)
VALUES('V' || LPAD(SEQ_VDNO.NEXTVAL, 9, '0'), 'radarstation@gmail.com', 'happymountain', '里程章', 'X102938475',
to_date('1999-12-31', 'yyyy-mm-dd'), '0966666666', '快樂山居露營區', '024681357', '新竹縣五峰鄉樂山大道1號', '91827364',
'88967726489371', 1, 0, 24.4973, 121.0704);

INSERT INTO VENDOR
(VD_NO, VD_EMAIL, VD_PWD, VD_NAME, VD_ID,
VD_BIRTH, VD_MOBILE, VD_CGNAME, VD_CGTEL, VD_CGADDR, VD_TAXID,
VD_ACC, VD_STAT, VD_CGSTAT, VD_LAT, VD_LON)
VALUES('V' || LPAD(SEQ_VDNO.NEXTVAL, 9, '0'), 'Myne@gmail.com', 'motosuurano', '梅茵', 'Y234567890',
to_date('1987-08-26', 'yyyy-mm-dd'), '0988888888', '古騰堡露營區', '037135246', '桃園市中壢區中大路300號', '98765432',
'00825540896783', 1, 0, 24.9679, 121.1922);

INSERT INTO VENDOR
(VD_NO, VD_EMAIL, VD_PWD, VD_NAME, VD_ID,
VD_BIRTH, VD_MOBILE, VD_CGNAME, VD_CGTEL, VD_CGADDR, VD_TAXID,
VD_ACC, VD_STAT, VD_CGSTAT, VD_LAT, VD_LON)
VALUES('V' || LPAD(SEQ_VDNO.NEXTVAL, 9, '0'), 'changpukong_daisuki@gmail.com', 'niconico123', '沉燕撫', 'A123456789',
to_date('1988-10-10', 'yyyy-mm-dd'), '0912345678', '本栖湖浩庵露營場', '024567890', '南投縣信義鄉東埔村一鄰玉山北峰1號', '13572468',
'12345678909876', 1, 1, 23.4878, 120.9595);

INSERT INTO VENDOR
(VD_NO, VD_EMAIL, VD_PWD, VD_NAME, VD_ID,
VD_BIRTH, VD_MOBILE, VD_CGNAME, VD_CGTEL, VD_CGADDR, VD_TAXID,
VD_ACC, VD_STAT, VD_CGSTAT, VD_LAT, VD_LON)
VALUES('V' || LPAD(SEQ_VDNO.NEXTVAL, 9, '0'), 'yurucamp@onsen.ag', 'yuru2021', '夏野小鳥無', 'K246789000',
to_date('1992-5-5', 'yyyy-mm-dd'), '0923098765', '陣馬形山露營地', '0377770033', '苗栗縣泰安鄉觀霧8號', '01013737',
'10293847566574', 1, 1, 24.5034, 121.1142);

INSERT INTO VENDOR
(VD_NO, VD_EMAIL, VD_PWD, VD_NAME, VD_ID,
VD_BIRTH, VD_MOBILE, VD_CGNAME, VD_CGTEL, VD_CGADDR, VD_TAXID,
VD_ACC, VD_STAT, VD_CGSTAT, VD_LAT, VD_LON)
VALUES('V' || LPAD(SEQ_VDNO.NEXTVAL, 9, '0'), 'nekodamari@houbunsha.co.jp', 'maru5566', '妝祈虹', 'Y299964488',
to_date('1984-2-29', 'yyyy-mm-dd'), '0977831183', '大雪山YMCA環球生態村', '083779453', '屏東縣牡丹鄉高士佛29號', '02041314',
'3141592653589793', 1, 1, 22.1227, 120.8389);

-- 插入營位類型資料
INSERT INTO CAMP_TYPE(CT_NO, CT_NAME)
VALUES('CT' || LPAD(SEQ_CTNO.NEXTVAL, 8, '0'), '室外');

INSERT INTO CAMP_TYPE(CT_NO, CT_NAME)
VALUES('CT' || LPAD(SEQ_CTNO.NEXTVAL, 8, '0'), '雨棚');

INSERT INTO CAMP_TYPE(CT_NO, CT_NAME)
VALUES('CT' || LPAD(SEQ_CTNO.NEXTVAL, 8, '0'), '小木屋');

INSERT INTO CAMP_TYPE(CT_NO, CT_NAME)
VALUES('CT' || LPAD(SEQ_CTNO.NEXTVAL, 8, '0'), '露營車');

INSERT INTO CAMP_TYPE(CT_NO, CT_NAME)
VALUES('CT' || LPAD(SEQ_CTNO.NEXTVAL, 8, '0'), '室內');

-- 插入營位資料
INSERT INTO CAMP
(CAMP_NO, CAMP_VDNO, CAMP_NAME, CAMP_CTNO, CAMP_QTY, CAMP_PRICE, CAMP_STAT)
VALUES('C' || LPAD(SEQ_CAMPNO.NEXTVAL, 9, '0'), 'V000000001', '大草坪', 'CT00000001', 20, 2000, 0);

INSERT INTO CAMP
(CAMP_NO, CAMP_VDNO, CAMP_NAME, CAMP_CTNO, CAMP_QTY, CAMP_PRICE, CAMP_STAT)
VALUES('C' || LPAD(SEQ_CAMPNO.NEXTVAL, 9, '0'), 'V000000001', '湖畔區', 'CT00000001', 10, 2500, 0);

INSERT INTO CAMP
(CAMP_NO, CAMP_VDNO, CAMP_NAME, CAMP_CTNO, CAMP_QTY, CAMP_PRICE, CAMP_STAT)
VALUES('C' || LPAD(SEQ_CAMPNO.NEXTVAL, 9, '0'), 'V000000001', '竹林區', 'CT00000001', 5, 3000, 0);

-- 插入裝備資料
INSERT INTO EQUIPMENT
(EQPT_NO, EQPT_VDNO, EQPT_NAME, EQPT_QTY, EQPT_PRICE, EQPT_STAT)
VALUES('E' || LPAD(SEQ_EQPTNO.NEXTVAL, 9, '0'), 'V000000001', '卡式瓦斯爐', 20, 100, 0);

INSERT INTO EQUIPMENT
(EQPT_NO, EQPT_VDNO, EQPT_NAME, EQPT_QTY, EQPT_PRICE, EQPT_STAT)
VALUES('E' || LPAD(SEQ_EQPTNO.NEXTVAL, 9, '0'), 'V000000001', '焚火台', 5, 250, 0);

INSERT INTO EQUIPMENT
(EQPT_NO, EQPT_VDNO, EQPT_NAME, EQPT_QTY, EQPT_PRICE, EQPT_STAT)
VALUES('E' || LPAD(SEQ_EQPTNO.NEXTVAL, 9, '0'), 'V000000001', '電暖器', 10, 300, 0);

INSERT INTO EQUIPMENT
(EQPT_NO, EQPT_VDNO, EQPT_NAME, EQPT_QTY, EQPT_PRICE, EQPT_STAT)
VALUES('E' || LPAD(SEQ_EQPTNO.NEXTVAL, 9, '0'), 'V000000001', '燈架', 10, 200, 0);

INSERT INTO EQUIPMENT
(EQPT_NO, EQPT_VDNO, EQPT_NAME, EQPT_QTY, EQPT_PRICE, EQPT_STAT)
VALUES('E' || LPAD(SEQ_EQPTNO.NEXTVAL, 9, '0'), 'V000000001', '大川椅', 20, 150, 0);

INSERT INTO EQUIPMENT
(EQPT_NO, EQPT_VDNO, EQPT_NAME, EQPT_QTY, EQPT_PRICE, EQPT_STAT)
VALUES('E' || LPAD(SEQ_EQPTNO.NEXTVAL, 9, '0'), 'V000000001', '羊毛毯', 10, 500, 0);

INSERT INTO EQUIPMENT
(EQPT_NO, EQPT_VDNO, EQPT_NAME, EQPT_QTY, EQPT_PRICE, EQPT_STAT)
VALUES('E' || LPAD(SEQ_EQPTNO.NEXTVAL, 9, '0'), 'V000000001', '釣竿', 25, 500, 0);

INSERT INTO EQUIPMENT
(EQPT_NO, EQPT_VDNO, EQPT_NAME, EQPT_QTY, EQPT_PRICE, EQPT_STAT)
VALUES('E' || LPAD(SEQ_EQPTNO.NEXTVAL, 9, '0'), 'V000000001', '充氣床墊', 15, 1000, 0);

INSERT INTO EQUIPMENT
(EQPT_NO, EQPT_VDNO, EQPT_NAME, EQPT_QTY, EQPT_PRICE, EQPT_STAT)
VALUES('E' || LPAD(SEQ_EQPTNO.NEXTVAL, 9, '0'), 'V000000001', '防水地墊', 30, 400, 0);

INSERT INTO EQUIPMENT
(EQPT_NO, EQPT_VDNO, EQPT_NAME, EQPT_QTY, EQPT_PRICE, EQPT_STAT)
VALUES('E' || LPAD(SEQ_EQPTNO.NEXTVAL, 9, '0'), 'V000000001', '客廳帳', 10, 1500, 0);

INSERT INTO EQUIPMENT
(EQPT_NO, EQPT_VDNO, EQPT_NAME, EQPT_QTY, EQPT_PRICE, EQPT_STAT)
VALUES('E' || LPAD(SEQ_EQPTNO.NEXTVAL, 9, '0'), 'V000000001', '天幕帳', 15, 800, 0);

INSERT INTO EQUIPMENT
(EQPT_NO, EQPT_VDNO, EQPT_NAME, EQPT_QTY, EQPT_PRICE, EQPT_STAT)
VALUES('E' || LPAD(SEQ_EQPTNO.NEXTVAL, 9, '0'), 'V000000001', '氣候達人四季帳篷', 10, 1200, 0);

INSERT INTO EQUIPMENT
(EQPT_NO, EQPT_VDNO, EQPT_NAME, EQPT_QTY, EQPT_PRICE, EQPT_STAT)
VALUES('E' || LPAD(SEQ_EQPTNO.NEXTVAL, 9, '0'), 'V000000001', '德爾瑪復古別墅帳', 10, 1500, 0);

INSERT INTO EQUIPMENT
(EQPT_NO, EQPT_VDNO, EQPT_NAME, EQPT_QTY, EQPT_PRICE, EQPT_STAT)
VALUES('E' || LPAD(SEQ_EQPTNO.NEXTVAL, 9, '0'), 'V000000001', '雙前庭帳篷', 10, 1000, 0);

INSERT INTO EQUIPMENT
(EQPT_NO, EQPT_VDNO, EQPT_NAME, EQPT_QTY, EQPT_PRICE, EQPT_STAT)
VALUES ('E' || LPAD(SEQ_EQPTNO.NEXTVAL, 9, '0'), 'V000000001', '四季通用輕巧迷你型睡袋', 20, 200, 0);

INSERT INTO EQUIPMENT
(EQPT_NO, EQPT_VDNO, EQPT_NAME, EQPT_QTY, EQPT_PRICE, EQPT_STAT)
VALUES ('E' || LPAD(SEQ_EQPTNO.NEXTVAL, 9, '0'), 'V000000001', 'ADISI EXPLORE 600 鵝絨睡袋', 20, 500, 0);

INSERT INTO EQUIPMENT
(EQPT_NO, EQPT_VDNO, EQPT_NAME, EQPT_QTY, EQPT_PRICE, EQPT_STAT)
VALUES ('E' || LPAD(SEQ_EQPTNO.NEXTVAL, 9, '0'), 'V000000001', '台灣製保暖防風防潑水羽絨睡袋', 20, 100, 0);

INSERT INTO EQUIPMENT
(EQPT_NO, EQPT_VDNO, EQPT_NAME, EQPT_QTY, EQPT_PRICE, EQPT_STAT)
VALUES ('E' || LPAD(SEQ_EQPTNO.NEXTVAL, 9, '0'), 'V000000001', '戶外露營折疊桌', 10, 300, 0);

INSERT INTO EQUIPMENT
(EQPT_NO, EQPT_VDNO, EQPT_NAME, EQPT_QTY, EQPT_PRICE, EQPT_STAT)
VALUES ('E' || LPAD(SEQ_EQPTNO.NEXTVAL, 9, '0'), 'V000000001', '鋁合金戶外折疊椅', 50, 100, 0);

INSERT INTO EQUIPMENT
(EQPT_NO, EQPT_VDNO, EQPT_NAME, EQPT_QTY, EQPT_PRICE, EQPT_STAT)
VALUES ('E' || LPAD(SEQ_EQPTNO.NEXTVAL, 9, '0'), 'V000000001', 'CPX6三合一LED桌燈', 10, 100, 0);

INSERT INTO EQUIPMENT
(EQPT_NO, EQPT_VDNO, EQPT_NAME, EQPT_QTY, EQPT_PRICE, EQPT_STAT)
VALUES ('E' || LPAD(SEQ_EQPTNO.NEXTVAL, 9, '0'), 'V000000001', '冰霸十日鮮冰桶(35公升)', 10, 100, 0);

-- 插入食材資料
INSERT INTO FOOD
(FOOD_NO, FOOD_VDNO, FOOD_NAME, FOOD_PRICE, FOOD_INTRO, FOOD_STAT)
VALUES('F' || LPAD(SEQ_FOODNO.NEXTVAL, 9, '0'), 'V000000003', '鳳尾蝦', 500,
'將核果搗碎後裹在蝦肉上，油炸成為金黃色，。鮮脆可口的核果外衣，經油炸之後，其香味立即倍增，堪稱人間第一美味，搭配特製醬汁來食用，味道更是妙不可言。跟醬汁巧妙的組合，正是這個炸蝦的精華所在。', 0);

INSERT INTO FOOD
(FOOD_NO, FOOD_VDNO, FOOD_NAME, FOOD_PRICE, FOOD_INTRO, FOOD_STAT)
VALUES('F' || LPAD(SEQ_FOODNO.NEXTVAL, 9, '0'), 'V000000003', '烏骨雞', 750,
'這不是招來不幸的雞，而是能為萬眾帶來幸福的雞。', 0);

INSERT INTO FOOD
(FOOD_NO, FOOD_VDNO, FOOD_NAME, FOOD_PRICE, FOOD_INTRO, FOOD_STAT)
VALUES('F' || LPAD(SEQ_FOODNO.NEXTVAL, 9, '0'), 'V000000003', '大魔術熊貓麻婆豆腐', 1000,
'六位一體的魔幻麻婆豆腐，是豆腐與肉的絕妙味覺合奏，就連四川菊下樓也未曾做出的絕妙料理。', 0);

INSERT INTO FOOD
(FOOD_NO, FOOD_VDNO, FOOD_NAME, FOOD_PRICE, FOOD_INTRO, FOOD_STAT)
VALUES('F' || LPAD(SEQ_FOODNO.NEXTVAL, 9, '0'), 'V000000001', '炎烤牛舌', 350,
'採用由CAS優良食品認證之電宰廠屠宰頂級燒烤食材首選牛舌，肉質Q彈、富有嚼勁燒烤後灑上岩鹽即是每位。', 2);

INSERT INTO FOOD
(FOOD_NO, FOOD_VDNO, FOOD_NAME, FOOD_PRICE, FOOD_INTRO, FOOD_STAT)
VALUES('F' || LPAD(SEQ_FOODNO.NEXTVAL, 9, '0'), 'V000000001', '嚴選雪花牛肉燒烤片', 350,
'嚴選進口牛肉，肉質鮮嫩多汁富有彈性，油花呈現雪花般紋路，口感紮實不油膩，是燒烤的最佳選擇。', 2);

INSERT INTO FOOD
(FOOD_NO, FOOD_VDNO, FOOD_NAME, FOOD_PRICE, FOOD_INTRO, FOOD_STAT)
VALUES('F' || LPAD(SEQ_FOODNO.NEXTVAL, 9, '0'), 'V000000001', '原味香腸', 95,
'精選CAS健康原料肉，結合現代化機器生產設備，通過嚴格衛生檢驗考驗，擁有HACCP合格認證。獨家配方，真實呈現飽滿肉質的風味，汁香味美口感十足。', 2);

INSERT INTO FOOD
(FOOD_NO, FOOD_VDNO, FOOD_NAME, FOOD_PRICE, FOOD_INTRO, FOOD_STAT)
VALUES('F' || LPAD(SEQ_FOODNO.NEXTVAL, 9, '0'), 'V000000001', '櫻桃鴨菲力', 180,
'鴨菲力為胸骨兩側的肌肉，一隻鴨只有2條，是全鴨最軟嫩的里肌部位。口感似牛菲力，肉質香甜多汁又鮮嫩，令人吮指回味。', 2);

INSERT INTO FOOD
(FOOD_NO, FOOD_VDNO, FOOD_NAME, FOOD_PRICE, FOOD_INTRO, FOOD_STAT)
VALUES('F' || LPAD(SEQ_FOODNO.NEXTVAL, 9, '0'), 'V000000001', '白刺蝦', 200,
'精選優質白刺蝦，為餐廳主廚之最愛，肉質細緻，味道甘甜，絕對讓您吃的鮮味十足，絕對美味。', 2);

INSERT INTO FOOD
(FOOD_NO, FOOD_VDNO, FOOD_NAME, FOOD_PRICE, FOOD_INTRO, FOOD_STAT)
VALUES('F' || LPAD(SEQ_FOODNO.NEXTVAL, 9, '0'), 'V000000001', '三五好友小聚組', 1331,
'1.西北烤肉醬2.礦泉水3.玉米串4.牛奶土司5.炭烤甜不辣片6.原味香腸7.醬燒里肌肉片8.蔥燒培根捲9.義式培根什蔬燒烤盒10.薄鹽鯖魚11.燒烤雞肉丸12.燒烤燕肉丸13.炭烤麻吉塊', 2);

INSERT INTO FOOD
(FOOD_NO, FOOD_VDNO, FOOD_NAME, FOOD_PRICE, FOOD_INTRO, FOOD_STAT)
VALUES('F' || LPAD(SEQ_FOODNO.NEXTVAL, 9, '0'), 'V000000001', '燒烤素食組', 1455,
'1.素烤肉醬2.玉米串3.牛奶土司4.冰烤番薯5.炭烤麻吉塊6.素香菇丸7.彩色甜椒盒8.杏鮑菇盒9.鮮香菇盒10.綜合地瓜11.四季豆+蘆筍+玉米筍12.奶油金針菇盒(蛋奶素)', 2);

INSERT INTO FOOD
(FOOD_NO, FOOD_VDNO, FOOD_NAME, FOOD_PRICE, FOOD_INTRO, FOOD_STAT)
VALUES('F' || LPAD(SEQ_FOODNO.NEXTVAL, 9, '0'), 'V000000001', '燒烤棉花糖(葷食)', 50,
'把軟呼呼甜膩膩的棉花糖，烤出一點焦黃，有點脆的外皮，派上融化燙口的中心，是大人小孩都無法拒絕的滋味。', 2);

INSERT INTO FOOD
(FOOD_NO, FOOD_VDNO, FOOD_NAME, FOOD_PRICE, FOOD_INTRO, FOOD_STAT)
VALUES('F' || LPAD(SEQ_FOODNO.NEXTVAL, 9, '0'), 'V000000001', '杏鮑菇盒', 119,
'杏鮑菇質地細膩，口感Q彈。燒烤時適當挑選合適蔬菜，能夠讓大家吃得更健康、更多元。', 2);

INSERT INTO FOOD(FOOD_NO, FOOD_VDNO, FOOD_NAME, FOOD_PRICE, FOOD_INTRO, FOOD_STAT)
VALUES('F' || LPAD(SEQ_FOODNO.NEXTVAL, 9, '0'), 'V000000001', '青椒盒', 70,
'青椒經過炭火慢烤後，口感清脆香甜。燒烤時適當挑選合適蔬菜，能夠讓大家吃得更健康、更多元。', 2);

-- 插入會員資料
INSERT INTO MEMBERS
(MEM_NO, MEM_EMAIL, MEM_PWD, MEM_NAME, MEM_ALIAS, MEM_GENDER,
MEM_BIRTH, MEM_MOBILE, MEM_TEL, MEM_ADDR, MEM_TYPE, MEM_STAT)
VALUES('M' || LPAD(SEQ_MEMNO.NEXTVAL, 9, '0'), '1@abc.com', '123', '莊麒弘', '傑夫', '男',
to_date('2002-01-01', 'yyyy-mm-dd'), '0910123456', '0071234567', '臺北市中正區黎明里北平西路3號', '1', '1');

INSERT INTO MEMBERS
(MEM_NO, MEM_EMAIL, MEM_PWD, MEM_NAME, MEM_ALIAS, MEM_GENDER,
MEM_BIRTH, MEM_MOBILE, MEM_TEL, MEM_ADDR, MEM_TYPE, MEM_STAT)
VALUES('M' || LPAD(SEQ_MEMNO.NEXTVAL, 9, '0'), '2@abc.com', '123', '陳彥甫', '手速最快的男人', '男',
to_date('2002-01-02', 'yyyy-mm-dd'), '0910123456', '0071234567', '新北市板橋區新民里縣民大道二段7號', '1', '1');

INSERT INTO MEMBERS
(MEM_NO, MEM_EMAIL, MEM_PWD, MEM_NAME, MEM_ALIAS, MEM_GENDER,
MEM_BIRTH, MEM_MOBILE, MEM_TEL, MEM_ADDR, MEM_TYPE, MEM_STAT)
VALUES('M' || LPAD(SEQ_MEMNO.NEXTVAL, 9, '0'), '3@abc.com', '123', '吳柏誼', '柏誼', '男',
to_date('2002-01-03', 'yyyy-mm-dd'), '0910123456', '0071234567', '基隆市中山區民治里1鄰中山一路16之1號', '1', '1');

INSERT INTO MEMBERS
(MEM_NO, MEM_EMAIL, MEM_PWD, MEM_NAME, MEM_ALIAS, MEM_GENDER,
MEM_BIRTH, MEM_MOBILE, MEM_TEL, MEM_ADDR, MEM_TYPE, MEM_STAT)
VALUES('M' || LPAD(SEQ_MEMNO.NEXTVAL, 9, '0'), '4@abc.com', '123', '顏敬家', 'Gaddis', '男',
to_date('2002-01-04', 'yyyy-mm-dd'), '0910123456', '0071234567', '基隆市七堵區長興里東新街2號', '1', '1');

INSERT INTO MEMBERS
(MEM_NO, MEM_EMAIL, MEM_PWD, MEM_NAME, MEM_ALIAS, MEM_GENDER,
MEM_BIRTH, MEM_MOBILE, MEM_TEL, MEM_ADDR, MEM_TYPE, MEM_STAT)
VALUES('M' || LPAD(SEQ_MEMNO.NEXTVAL, 9, '0'), '5@abc.com', '123', '顏敬修', 'Hugh', '男',
to_date('2002-01-04', 'yyyy-mm-dd'), '0910123456', '0071234567', '新北市樹林區樹北里鎮前街112號', '1', '1');

INSERT INTO MEMBERS
(MEM_NO, MEM_EMAIL, MEM_PWD, MEM_NAME, MEM_ALIAS, MEM_GENDER, MEM_BIRTH,
MEM_MOBILE, MEM_TEL, MEM_ADDR, MEM_TYPE, MEM_STAT)
VALUES('M' || LPAD(SEQ_MEMNO.NEXTVAL, 9, '0'), '6@abc.com', '123', '夏孟勤', '大園黃捷', '女',
to_date('2002-01-05', 'yyyy-mm-dd'), '0910123456', '0071234567', '新北市瑞芳區龍潭里明燈路三段82號', '1', '1');

INSERT INTO MEMBERS
(MEM_NO, MEM_EMAIL, MEM_PWD, MEM_NAME, MEM_ALIAS, MEM_GENDER, MEM_BIRTH,
MEM_MOBILE, MEM_TEL, MEM_ADDR, MEM_TYPE, MEM_STAT)
VALUES('M' || LPAD(SEQ_MEMNO.NEXTVAL, 9, '0'), '7@abc.com', '123', '李承璋', 'Kevin', '男',
to_date('2002-01-06', 'yyyy-mm-dd'), '0910123456', '0071234567', '新北市平溪區平溪里中華街12號', '1', '1');

INSERT INTO MEMBERS
(MEM_NO, MEM_EMAIL, MEM_PWD, MEM_NAME, MEM_ALIAS, MEM_GENDER,
MEM_BIRTH, MEM_MOBILE, MEM_TEL, MEM_ADDR, MEM_TYPE, MEM_STAT)
VALUES('M' || LPAD(SEQ_MEMNO.NEXTVAL, 9, '0'), '8@abc.com', '123', '鄭宇翔', 'Joe', '男',
to_date('2002-01-07', 'yyyy-mm-dd'), '0910123456', '0071234567', '新北市瑞芳區光復里柴寮路70號', '1', '1');

INSERT INTO MEMBERS
(MEM_NO, MEM_EMAIL, MEM_PWD, MEM_NAME, MEM_ALIAS, MEM_GENDER,
MEM_BIRTH, MEM_MOBILE, MEM_TEL, MEM_ADDR, MEM_TYPE, MEM_STAT)
VALUES('M' || LPAD(SEQ_MEMNO.NEXTVAL, 9, '0'), '9@abc.com', '123', '卓宜潔', '萬華郭采潔', '女',
to_date('2002-01-08', 'yyyy-mm-dd'), '0910123456', '0071234567', '臺北市萬華區富福里康定路382號', '1', '1');

INSERT INTO MEMBERS
(MEM_NO, MEM_EMAIL, MEM_PWD, MEM_NAME, MEM_ALIAS, MEM_GENDER,
MEM_BIRTH, MEM_MOBILE, MEM_TEL, MEM_ADDR, MEM_TYPE, MEM_STAT)
VALUES('M' || LPAD(SEQ_MEMNO.NEXTVAL, 9, '0'), '10@abc.com', '123', '馮貽傑', 'EJ的西風之神', '男',
to_date('2002-01-09', 'yyyy-mm-dd'), '0910123456', '0071234567', '桃園市桃園區武陵里中正路1號', '1', '1');

-- 插入管理員資料
INSERT INTO ADMINIS
(ADMINIS_NO, ADMINIS_NAME, ADMINIS_PWD, ADMINIS_EMAIL, ADMINIS_DEPT, ADMINIS_PV) 
VALUES('A' || LPAD(SEQ_ADMINISNO.NEXTVAL, 9, '0'), '吳永志', '123456', 'ea103@gmail.com', '管理部', 2047);

INSERT INTO ADMINIS
(ADMINIS_NO,ADMINIS_NAME,ADMINIS_PWD,ADMINIS_EMAIL,ADMINIS_DEPT,ADMINIS_PV) 
VALUES ('A' || LPAD(SEQ_ADMINISNO.NEXTVAL, 9, '0'), '吳冠宏', '123456', 'ea103_1@gmail.com', '管理部', 2047);

INSERT INTO ADMINIS
(ADMINIS_NO,ADMINIS_NAME,ADMINIS_PWD,ADMINIS_EMAIL,ADMINIS_DEPT,ADMINIS_PV) 
VALUES ('A' || LPAD(SEQ_ADMINISNO.NEXTVAL, 9, '0'), '吳柏誼', '123456', 'ea103_2@gmail.com', '管理部', 1257);

INSERT INTO ADMINIS
(ADMINIS_NO,ADMINIS_NAME,ADMINIS_PWD,ADMINIS_EMAIL,ADMINIS_DEPT,ADMINIS_PV) 
VALUES ('A' || LPAD(SEQ_ADMINISNO.NEXTVAL, 9, '0'), '陳彥甫', '123456', 'ea103_3@gmail.com', '管理部', 1452);

INSERT INTO ADMINIS
(ADMINIS_NO,ADMINIS_NAME,ADMINIS_PWD,ADMINIS_EMAIL,ADMINIS_DEPT,ADMINIS_PV) 
VALUES ('A' || LPAD(SEQ_ADMINISNO.NEXTVAL, 9, '0'), '莊麒弘', '123456', 'ea103_4@gmail.com', '管理部', 1434);

INSERT INTO ADMINIS
(ADMINIS_NO,ADMINIS_NAME,ADMINIS_PWD,ADMINIS_EMAIL,ADMINIS_DEPT,ADMINIS_PV) 
VALUES ('A' || LPAD(SEQ_ADMINISNO.NEXTVAL, 9, '0'), '李承璋', '123456', 'ea103_5@gmail.com', '管理部', 1287);

INSERT INTO ADMINIS
(ADMINIS_NO,ADMINIS_NAME,ADMINIS_PWD,ADMINIS_EMAIL,ADMINIS_DEPT,ADMINIS_PV) 
VALUES ('A' || LPAD(SEQ_ADMINISNO.NEXTVAL, 9, '0'), '顏敬修', '123456', 'ea103_6@gmail.com', '管理部', 1287);

INSERT INTO ADMINIS
(ADMINIS_NO,ADMINIS_NAME,ADMINIS_PWD,ADMINIS_EMAIL,ADMINIS_DEPT,ADMINIS_PV) 
VALUES ('A' || LPAD(SEQ_ADMINISNO.NEXTVAL, 9, '0'), '顏敬家', '123456', 'ea103_7@gmail.com', '管理部', 1287);

INSERT INTO ADMINIS
(ADMINIS_NO,ADMINIS_NAME,ADMINIS_PWD,ADMINIS_EMAIL,ADMINIS_DEPT,ADMINIS_PV) 
VALUES ('A' || LPAD(SEQ_ADMINISNO.NEXTVAL, 9, '0'), '夏孟勤', '123456', 'ea103_8@gmail.com', '管理部', 1287);

-- 插入權限資料
INSERT INTO AUTHORITY
(AUTH_NO, AUTH_NAME)
VALUES(SEQ_AUTHNO.NEXTVAL, '權限管理');

INSERT INTO AUTHORITY
(AUTH_NO, AUTH_NAME)
VALUES(SEQ_AUTHNO.NEXTVAL, '管理員管理');

INSERT INTO AUTHORITY
(AUTH_NO, AUTH_NAME)
VALUES(SEQ_AUTHNO.NEXTVAL, '收支管理');

INSERT INTO AUTHORITY
(AUTH_NO, AUTH_NAME)
VALUES(SEQ_AUTHNO.NEXTVAL, '文章檢舉管理');

INSERT INTO AUTHORITY
(AUTH_NO, AUTH_NAME)
VALUES(SEQ_AUTHNO.NEXTVAL, 'FAQ管理');

INSERT INTO AUTHORITY
(AUTH_NO, AUTH_NAME)
VALUES(SEQ_AUTHNO.NEXTVAL, '活動快報管理');

INSERT INTO AUTHORITY
(AUTH_NO, AUTH_NAME)
VALUES(SEQ_AUTHNO.NEXTVAL, '裝備介紹管理');

INSERT INTO AUTHORITY
(AUTH_NO, AUTH_NAME)
VALUES(SEQ_AUTHNO.NEXTVAL, '露營指南管理');

INSERT INTO AUTHORITY
(AUTH_NO, AUTH_NAME)
VALUES(SEQ_AUTHNO.NEXTVAL, '廠商帳號審核');

INSERT INTO AUTHORITY
(AUTH_NO, AUTH_NAME)
VALUES(SEQ_AUTHNO.NEXTVAL, '會員停權管理');

INSERT INTO AUTHORITY
(AUTH_NO, AUTH_NAME)
VALUES(SEQ_AUTHNO.NEXTVAL, '會員資料管理');

-- 插入瀑布牆文章
INSERT INTO WATERFALL
(WF_NO, WF_MEMNO, WF_TITLE, WF_CONTENT)
VALUES('W' || LPAD(SEQ_WFNO.NEXTVAL, 9, '0'), 'M000000001', '[分享] 苗栗露營營地。遊牧民族露營區',
'帶著我的新買的Coleman 印地安帳篷、迪卡儂加大款蝶式天幕來苗栗的遊牧民族露營區開箱囉!遊牧民族露營區的環境維持得非常整潔，沒甚麼蚊蟲，
還有漂亮的草地，在這裡坐在樹下甚麼事都不做吹著徐徐涼風，就已經非常舒服~
從台北開到苗栗大約2小時，遊牧民族露營區就在洗水坑豆腐街(清安豆腐老街)附近，附近也有不少知名溫泉旅館。
果然是非常熱門的營地，周末熱鬧滾滾!
車子可以停在帳篷附近，拿東西很方便!浴室廁所也很近!而且一直有人在打掃，每次去都覺得很乾淨!熱水也不會忽冷忽熱。
有水池、沙坑、溜滑梯等設施，很適合帶小朋友來這裡玩!
每帳旁邊都有一個專用的洗手台和垃圾桶。
這次是我的第二露!上次在桃園八度野溪露營區，也非常棒!這兩個露營區都很適合全家同遊!由於非常搶手，建議大家要提早預訂!');

INSERT INTO WATERFALL
(WF_NO, WF_MEMNO, WF_TITLE, WF_CONTENT)
VALUES('W' || LPAD(SEQ_WFNO.NEXTVAL, 9, '0'), 'M000000002', '[請益] 黑岩谷和岩谷4.1瓦斯爐選擇',
'板上討論的大多是岩谷4.1kw (CB-AH-41),比較少人討論到黑岩谷3.3kw (CB-ODX-1),如果再選擇一次大家會買黑岩谷岩谷嗎？
有兩台都用過的心得？
店員說黑岩谷賣比較好不知道是不是真的？');

INSERT INTO WATERFALL
(WF_NO, WF_MEMNO, WF_TITLE, WF_CONTENT)
VALUES('W' || LPAD(SEQ_WFNO.NEXTVAL, 9, '0'), 'M000000003', '[請益] 中部以北可釣魚親子露營',
'我們是高中同學四個女生攜伴想去露營，但是只有一兩次經驗，兩個已經結婚有小孩，兩個有穩定交往對象，所以對營區的希望會不太一樣，覺得好難找，
不然就是沒位了嗚嗚嗚......希望有經驗的版友推薦。
必要條件:中部以北、可釣魚、有一點親子設施（玩水或滑草之類的），衛浴設備乾淨、有雨棚營位或是露營車。
非必要條件:有小木屋或住宿區（不需搭帳）。
拜託大家推薦了，無比感謝！');

INSERT INTO WATERFALL
(WF_NO, WF_MEMNO, WF_TITLE, WF_CONTENT)
VALUES('W' || LPAD(SEQ_WFNO.NEXTVAL, 9, '0'), 'M000000004','[請益] kazmi露營桌',
'目前露營是只有跟另一半兩人簡單的露，
現在使用的桌子是下面這種比較簡易的，不過因為沒防水，表面已經有點起泡，
椅子也被凌虐的差不多XD
正考慮升級一下，最近在考慮kazmi的這款鋼網桌，想請問板上各位是否有使用心得可以參考！
或有推薦其他好用好攜帶的露營桌？！
（蛋捲桌有攜帶上的問題目前是不考慮）
感謝各位！');

INSERT INTO WATERFALL
(WF_NO, WF_MEMNO, WF_TITLE, WF_CONTENT)
VALUES('W' || LPAD(SEQ_WFNO.NEXTVAL, 9, '0'), 'M000000005','[分享] 新竹尖石熊麻吉露營區',
'新竹尖石的熊麻吉露營區，從內灣過去路程還算好走。
營區內可容納三十餘帳，草皮已有鋪好護草墊，營主非常熱情，不時舉辦親子同樂活動。
營區內有溜滑梯與游泳池，對於小朋友來說是個放電的好設施！
周遭依山傍水，附近即有小溪可以遊憩，但要前往須注意安全，尤其是夜晚要抓溪蝦的話，最好找人陪同！
本次我有下去抓，有點可怕XD個人較為介意的點有二：
一、營位距離較小。若是幾帳熟識倒還好，但如果隔壁是不認識的，可能一點聲音就聽得到。
二、洗澡淋浴水壓與水溫不穩：即使在離峰時間盥洗，建議仍須將水放至水桶沖洗，無法以淋浴的方式洗澡，否則不是燙死就是冷死XD
另外水桶數量似乎不齊全，那天我們同行的小朋友有燙到@@
整體來說是個親子同遊的好去處，但如果喜歡大景或是享受高海拔風情，則不符合需求！還是建議大家可以前去體驗看看哦！
附上本次露營Youtube影片連結：https://youtu.be/XU3HqaY6SZA');

-- 插入文章回覆
INSERT INTO WF_REPLY
(WFR_NO, WFR_WFNO, WFR_MEMNO, WFR_CONTENT)
VALUES('WR' || LPAD(SEQ_WFRNO.NEXTVAL, 8, '0'), 'W000000001', 'M000000006', '讚喔');

INSERT INTO WF_REPLY
(WFR_NO, WFR_WFNO, WFR_MEMNO, WFR_CONTENT)
VALUES('WR' || LPAD(SEQ_WFRNO.NEXTVAL, 8, '0'), 'W000000002', 'M000000007', '如果讓我重選我會選黑岩谷，尤其近期開始特價了');

INSERT INTO WF_REPLY
(WFR_NO, WFR_WFNO, WFR_MEMNO, WFR_CONTENT)
VALUES('WR' || LPAD(SEQ_WFRNO.NEXTVAL, 8, '0'), 'W000000003', 'M000000008', '埔里，幸埔森，還可以撿雞蛋');

INSERT INTO WF_REPLY
(WFR_NO, WFR_WFNO, WFR_MEMNO, WFR_CONTENT)
VALUES('WR' || LPAD(SEQ_WFRNO.NEXTVAL, 8, '0'), 'W000000004', 'M000000009', '我是用箱子當桌子，也可以收納雜物');

INSERT INTO WF_REPLY
(WFR_NO, WFR_WFNO, WFR_MEMNO, WFR_CONTENT)
VALUES('WR' || LPAD(SEQ_WFRNO.NEXTVAL, 8, '0'), 'W000000004', 'M000000010', '我當時在MOMO買3100的樣子,不然就買 國士無雙啦!!!!');

-- 插入露營區介紹
INSERT INTO CG_INTRO
(CGI_NO, CGI_VDNO, CGI_CONTENT)
VALUES('I' || LPAD(SEQ_CGINO.NEXTVAL, 9, '0'), 'V000000001',
'【蘿菈松靜露營區】位於苗栗縣南庄鄉，海拔720公尺。遠離南庄鬧區，獨立於往鹿場路上的一片原始林中，原址為前蘿菈農場，正在過退休生活的營主，整理部分園區除了讓兄弟姊妹上來喝茶聊天，好客的營主家人們也以對待朋友、家人的心情，迎接每個到來的"朗尼"(泰雅族語朋友)，也使得松靜除了自然氣息外，也添加了份濃濃的人情味。');

commit;